// TODO Migration Pending

plugins {
  id 'com.android.application'
}

android {
  namespace "com.afterroot.allusive_rro"
  compileSdk 37

  defaultConfig {
    applicationId "com.afterroot.allusive_rro"
    minSdk 30
    targetSdk 37
    versionCode 2
    versionName "2.0"
  }

  buildFeatures {
    buildConfig = false
    resValues = false
  }

  def keystorePropertiesFile = rootProject.file("local.properties")
  def keystoreProperties = new Properties()
  if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
  }

  signingConfigs {
    allusive {
      keyAlias "allusive"
      keyPassword keystoreProperties['keyPassword'] ?: System.getenv("SIGN_KEY_PW")
      storeFile rootProject.file("release/keystore.jks")
      storePassword keystoreProperties['storePassword'] ?: System.getenv("SIGN_STORE_PW")
    }
  }

  buildTypes {
    release {
      minifyEnabled false
      shrinkResources false
      crunchPngs false
      signingConfig signingConfigs.allusive
      //proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
    debug {
      signingConfig signingConfigs.allusive
    }
  }
}
